name:                modules
version:             0.1.0.0
github:              "elpinal/modules"
license:             MIT
author:              "El Pin Al"
maintainer:          ""
copyright:           "2018 El Pin Al"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elpinal/modules#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.11.0
- freer-simple >= 1.1.0.0

library:
  source-dirs: src
  default-extensions:
  - FlexibleContexts

tests:
  modules-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modules
    - hspec >= 2.5.5
