name:                modules
version:             0.1.0.0
github:              "elpinal/modules"
license:             MIT
author:              "El Pin Al"
maintainer:          ""
copyright:           "2018 El Pin Al"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elpinal/modules#readme>

dependencies:
- base >= 4.7 && < 5
- comonad >= 5.0.5
- containers >= 0.5.11.0
- directory >= 1.3.3.0
- filepath >= 1.4.2.1
- freer-simple >= 1.1.0.0
- megaparsec >= 7.0.4
- mtl >= 2.2.2
- optparse-applicative >= 0.14.3.0
- parser-combinators >= 1.0.1
- polysemy >= 0.4.0.0
- polysemy-plugin >= 0.2.1.0
- prettyprinter >= 1.2.1
- safe-exceptions >= 0.1.7.0
- template-haskell >= 2.14.0.0
- text >= 1.2.3.1

library:
  source-dirs: src
  default-extensions:
  - FlexibleContexts

executables:
  1mlex:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modules

tests:
  modules-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modules
    - hspec >= 2.5.5
  integration:
    main:                Main.hs
    source-dirs:         test/integration
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modules
    - hspec >= 2.5.5
    - raw-strings-qq >= 1.1
